[workspace]
authors = ["Allen Guo <guosonglin001@gmail.com>"]
channels = ["conda-forge"]
name = "asm_demos"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
# mlir = ">=21.1.8,<22"

[activation.env]
# https://github.com/gglin001/llvm-mlir
PATH_0 = "${PIXI_PROJECT_ROOT}/llvm-mlir/llvm-project/build/bin"
PATH_1 = "${PIXI_PROJECT_ROOT}/llvm-mlir/llvm-project/build/bin"
PATH = "${PATH_0}:${PATH_1}:${PATH}"
